// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyProductAttribute("HalKit")]
[assembly: AssemblyCompanyAttribute("viagogo")]
[assembly: AssemblyCopyrightAttribute("Copyright viagogo 2018")]
[assembly: AssemblyVersionAttribute("0.9")]
[assembly: AssemblyFileVersionAttribute("0.9")]
[assembly: AssemblyInformationalVersionAttribute("0.9")]
[assembly: ComVisibleAttribute(false)]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.9";
    }
}
